// configTestnet.js
export const providerRpcUrlTestnet = 'https://rpc.ankr.com/base_sepolia';
export const linkTokenBaseSpolia = "0xE4aB69C077896252FAFBD49EFD26B5D171A32410";
export const private_key = 'private_key';
export const private_key_format = 'private_key';
export const uniswapSepholiaTestnetRouterContractAddress = '0xC532a74256D3Db42D0Bf7a0400fEFDbad7694008';
export const ethTestnet ="0x1b44F3514812d835EB1BDB0acB33d3fA3351Ee43"
export const wethTestnet ="0x4200000000000000000000000000000000000006"
export const uniswapv2TestnetSepholia_abi = [
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_factory",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"_WETH",
            "type":"address"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"constructor"
   },
   {
      "inputs":[
         
      ],
      "name":"WETH",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"tokenA",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"tokenB",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"amountADesired",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"amountBDesired",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"amountAMin",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"amountBMin",
            "type":"uint256"
         },
         {
            "internalType":"address",
            "name":"to",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"deadline",
            "type":"uint256"
         }
      ],
      "name":"addLiquidity",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"amountA",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"amountB",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"liquidity",
            "type":"uint256"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"token",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"amountTokenDesired",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"amountTokenMin",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"amountETHMin",
            "type":"uint256"
         },
         {
            "internalType":"address",
            "name":"to",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"deadline",
            "type":"uint256"
         }
      ],
      "name":"addLiquidityETH",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"amountToken",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"amountETH",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"liquidity",
            "type":"uint256"
         }
      ],
      "stateMutability":"payable",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"factory",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"amountOut",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"reserveIn",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"reserveOut",
            "type":"uint256"
         }
      ],
      "name":"getAmountIn",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"amountIn",
            "type":"uint256"
         }
      ],
      "stateMutability":"pure",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"amountIn",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"reserveIn",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"reserveOut",
            "type":"uint256"
         }
      ],
      "name":"getAmountOut",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"amountOut",
            "type":"uint256"
         }
      ],
      "stateMutability":"pure",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"amountOut",
            "type":"uint256"
         },
         {
            "internalType":"address[]",
            "name":"path",
            "type":"address[]"
         }
      ],
      "name":"getAmountsIn",
      "outputs":[
         {
            "internalType":"uint256[]",
            "name":"amounts",
            "type":"uint256[]"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"amountIn",
            "type":"uint256"
         },
         {
            "internalType":"address[]",
            "name":"path",
            "type":"address[]"
         }
      ],
      "name":"getAmountsOut",
      "outputs":[
         {
            "internalType":"uint256[]",
            "name":"amounts",
            "type":"uint256[]"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"amountA",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"reserveA",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"reserveB",
            "type":"uint256"
         }
      ],
      "name":"quote",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"amountB",
            "type":"uint256"
         }
      ],
      "stateMutability":"pure",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"tokenA",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"tokenB",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"liquidity",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"amountAMin",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"amountBMin",
            "type":"uint256"
         },
         {
            "internalType":"address",
            "name":"to",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"deadline",
            "type":"uint256"
         }
      ],
      "name":"removeLiquidity",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"amountA",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"amountB",
            "type":"uint256"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"token",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"liquidity",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"amountTokenMin",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"amountETHMin",
            "type":"uint256"
         },
         {
            "internalType":"address",
            "name":"to",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"deadline",
            "type":"uint256"
         }
      ],
      "name":"removeLiquidityETH",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"amountToken",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"amountETH",
            "type":"uint256"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"token",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"liquidity",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"amountTokenMin",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"amountETHMin",
            "type":"uint256"
         },
         {
            "internalType":"address",
            "name":"to",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"deadline",
            "type":"uint256"
         }
      ],
      "name":"removeLiquidityETHSupportingFeeOnTransferTokens",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"amountETH",
            "type":"uint256"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"token",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"liquidity",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"amountTokenMin",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"amountETHMin",
            "type":"uint256"
         },
         {
            "internalType":"address",
            "name":"to",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"deadline",
            "type":"uint256"
         },
         {
            "internalType":"bool",
            "name":"approveMax",
            "type":"bool"
         },
         {
            "internalType":"uint8",
            "name":"v",
            "type":"uint8"
         },
         {
            "internalType":"bytes32",
            "name":"r",
            "type":"bytes32"
         },
         {
            "internalType":"bytes32",
            "name":"s",
            "type":"bytes32"
         }
      ],
      "name":"removeLiquidityETHWithPermit",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"amountToken",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"amountETH",
            "type":"uint256"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"token",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"liquidity",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"amountTokenMin",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"amountETHMin",
            "type":"uint256"
         },
         {
            "internalType":"address",
            "name":"to",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"deadline",
            "type":"uint256"
         },
         {
            "internalType":"bool",
            "name":"approveMax",
            "type":"bool"
         },
         {
            "internalType":"uint8",
            "name":"v",
            "type":"uint8"
         },
         {
            "internalType":"bytes32",
            "name":"r",
            "type":"bytes32"
         },
         {
            "internalType":"bytes32",
            "name":"s",
            "type":"bytes32"
         }
      ],
      "name":"removeLiquidityETHWithPermitSupportingFeeOnTransferTokens",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"amountETH",
            "type":"uint256"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"tokenA",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"tokenB",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"liquidity",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"amountAMin",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"amountBMin",
            "type":"uint256"
         },
         {
            "internalType":"address",
            "name":"to",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"deadline",
            "type":"uint256"
         },
         {
            "internalType":"bool",
            "name":"approveMax",
            "type":"bool"
         },
         {
            "internalType":"uint8",
            "name":"v",
            "type":"uint8"
         },
         {
            "internalType":"bytes32",
            "name":"r",
            "type":"bytes32"
         },
         {
            "internalType":"bytes32",
            "name":"s",
            "type":"bytes32"
         }
      ],
      "name":"removeLiquidityWithPermit",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"amountA",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"amountB",
            "type":"uint256"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"amountOut",
            "type":"uint256"
         },
         {
            "internalType":"address[]",
            "name":"path",
            "type":"address[]"
         },
         {
            "internalType":"address",
            "name":"to",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"deadline",
            "type":"uint256"
         }
      ],
      "name":"swapETHForExactTokens",
      "outputs":[
         {
            "internalType":"uint256[]",
            "name":"amounts",
            "type":"uint256[]"
         }
      ],
      "stateMutability":"payable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"amountOutMin",
            "type":"uint256"
         },
         {
            "internalType":"address[]",
            "name":"path",
            "type":"address[]"
         },
         {
            "internalType":"address",
            "name":"to",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"deadline",
            "type":"uint256"
         }
      ],
      "name":"swapExactETHForTokens",
      "outputs":[
         {
            "internalType":"uint256[]",
            "name":"amounts",
            "type":"uint256[]"
         }
      ],
      "stateMutability":"payable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"amountOutMin",
            "type":"uint256"
         },
         {
            "internalType":"address[]",
            "name":"path",
            "type":"address[]"
         },
         {
            "internalType":"address",
            "name":"to",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"deadline",
            "type":"uint256"
         }
      ],
      "name":"swapExactETHForTokensSupportingFeeOnTransferTokens",
      "outputs":[
         
      ],
      "stateMutability":"payable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"amountIn",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"amountOutMin",
            "type":"uint256"
         },
         {
            "internalType":"address[]",
            "name":"path",
            "type":"address[]"
         },
         {
            "internalType":"address",
            "name":"to",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"deadline",
            "type":"uint256"
         }
      ],
      "name":"swapExactTokensForETH",
      "outputs":[
         {
            "internalType":"uint256[]",
            "name":"amounts",
            "type":"uint256[]"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"amountIn",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"amountOutMin",
            "type":"uint256"
         },
         {
            "internalType":"address[]",
            "name":"path",
            "type":"address[]"
         },
         {
            "internalType":"address",
            "name":"to",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"deadline",
            "type":"uint256"
         }
      ],
      "name":"swapExactTokensForETHSupportingFeeOnTransferTokens",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"amountIn",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"amountOutMin",
            "type":"uint256"
         },
         {
            "internalType":"address[]",
            "name":"path",
            "type":"address[]"
         },
         {
            "internalType":"address",
            "name":"to",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"deadline",
            "type":"uint256"
         }
      ],
      "name":"swapExactTokensForTokens",
      "outputs":[
         {
            "internalType":"uint256[]",
            "name":"amounts",
            "type":"uint256[]"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"amountIn",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"amountOutMin",
            "type":"uint256"
         },
         {
            "internalType":"address[]",
            "name":"path",
            "type":"address[]"
         },
         {
            "internalType":"address",
            "name":"to",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"deadline",
            "type":"uint256"
         }
      ],
      "name":"swapExactTokensForTokensSupportingFeeOnTransferTokens",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"amountOut",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"amountInMax",
            "type":"uint256"
         },
         {
            "internalType":"address[]",
            "name":"path",
            "type":"address[]"
         },
         {
            "internalType":"address",
            "name":"to",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"deadline",
            "type":"uint256"
         }
      ],
      "name":"swapTokensForExactETH",
      "outputs":[
         {
            "internalType":"uint256[]",
            "name":"amounts",
            "type":"uint256[]"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"amountOut",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"amountInMax",
            "type":"uint256"
         },
         {
            "internalType":"address[]",
            "name":"path",
            "type":"address[]"
         },
         {
            "internalType":"address",
            "name":"to",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"deadline",
            "type":"uint256"
         }
      ],
      "name":"swapTokensForExactTokens",
      "outputs":[
         {
            "internalType":"uint256[]",
            "name":"amounts",
            "type":"uint256[]"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "stateMutability":"payable",
      "type":"receive"
   }
];
export const linkabi = [
   {
      "inputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"constructor"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"supplyAfterMint",
            "type":"uint256"
         }
      ],
      "name":"MaxSupplyExceeded",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"sender",
            "type":"address"
         }
      ],
      "name":"SenderNotBurner",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"sender",
            "type":"address"
         }
      ],
      "name":"SenderNotMinter",
      "type":"error"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"owner",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"spender",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"value",
            "type":"uint256"
         }
      ],
      "name":"Approval",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"burner",
            "type":"address"
         }
      ],
      "name":"BurnAccessGranted",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"burner",
            "type":"address"
         }
      ],
      "name":"BurnAccessRevoked",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"minter",
            "type":"address"
         }
      ],
      "name":"MintAccessGranted",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"minter",
            "type":"address"
         }
      ],
      "name":"MintAccessRevoked",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"from",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"to",
            "type":"address"
         }
      ],
      "name":"OwnershipTransferRequested",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"from",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"to",
            "type":"address"
         }
      ],
      "name":"OwnershipTransferred",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"from",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"to",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"value",
            "type":"uint256"
         }
      ],
      "name":"Transfer",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"from",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"to",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"value",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"bytes",
            "name":"data",
            "type":"bytes"
         }
      ],
      "name":"Transfer",
      "type":"event"
   },
   {
      "inputs":[
         
      ],
      "name":"acceptOwnership",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"owner",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"spender",
            "type":"address"
         }
      ],
      "name":"allowance",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"spender",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"amount",
            "type":"uint256"
         }
      ],
      "name":"approve",
      "outputs":[
         {
            "internalType":"bool",
            "name":"",
            "type":"bool"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"account",
            "type":"address"
         }
      ],
      "name":"balanceOf",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"amount",
            "type":"uint256"
         }
      ],
      "name":"burn",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"account",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"amount",
            "type":"uint256"
         }
      ],
      "name":"burn",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"account",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"amount",
            "type":"uint256"
         }
      ],
      "name":"burnFrom",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"decimals",
      "outputs":[
         {
            "internalType":"uint8",
            "name":"",
            "type":"uint8"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"spender",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"subtractedValue",
            "type":"uint256"
         }
      ],
      "name":"decreaseAllowance",
      "outputs":[
         {
            "internalType":"bool",
            "name":"",
            "type":"bool"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"spender",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"subtractedValue",
            "type":"uint256"
         }
      ],
      "name":"decreaseApproval",
      "outputs":[
         {
            "internalType":"bool",
            "name":"success",
            "type":"bool"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"getBurners",
      "outputs":[
         {
            "internalType":"address[]",
            "name":"",
            "type":"address[]"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"getMinters",
      "outputs":[
         {
            "internalType":"address[]",
            "name":"",
            "type":"address[]"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"burner",
            "type":"address"
         }
      ],
      "name":"grantBurnRole",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"burnAndMinter",
            "type":"address"
         }
      ],
      "name":"grantMintAndBurnRoles",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"minter",
            "type":"address"
         }
      ],
      "name":"grantMintRole",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"spender",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"addedValue",
            "type":"uint256"
         }
      ],
      "name":"increaseAllowance",
      "outputs":[
         {
            "internalType":"bool",
            "name":"",
            "type":"bool"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"spender",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"addedValue",
            "type":"uint256"
         }
      ],
      "name":"increaseApproval",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"burner",
            "type":"address"
         }
      ],
      "name":"isBurner",
      "outputs":[
         {
            "internalType":"bool",
            "name":"",
            "type":"bool"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"minter",
            "type":"address"
         }
      ],
      "name":"isMinter",
      "outputs":[
         {
            "internalType":"bool",
            "name":"",
            "type":"bool"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"maxSupply",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"account",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"amount",
            "type":"uint256"
         }
      ],
      "name":"mint",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"name",
      "outputs":[
         {
            "internalType":"string",
            "name":"",
            "type":"string"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"owner",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"burner",
            "type":"address"
         }
      ],
      "name":"revokeBurnRole",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"minter",
            "type":"address"
         }
      ],
      "name":"revokeMintRole",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"bytes4",
            "name":"interfaceId",
            "type":"bytes4"
         }
      ],
      "name":"supportsInterface",
      "outputs":[
         {
            "internalType":"bool",
            "name":"",
            "type":"bool"
         }
      ],
      "stateMutability":"pure",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"symbol",
      "outputs":[
         {
            "internalType":"string",
            "name":"",
            "type":"string"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"totalSupply",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"to",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"amount",
            "type":"uint256"
         }
      ],
      "name":"transfer",
      "outputs":[
         {
            "internalType":"bool",
            "name":"",
            "type":"bool"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"to",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"amount",
            "type":"uint256"
         },
         {
            "internalType":"bytes",
            "name":"data",
            "type":"bytes"
         }
      ],
      "name":"transferAndCall",
      "outputs":[
         {
            "internalType":"bool",
            "name":"success",
            "type":"bool"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"from",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"to",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"amount",
            "type":"uint256"
         }
      ],
      "name":"transferFrom",
      "outputs":[
         {
            "internalType":"bool",
            "name":"",
            "type":"bool"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"to",
            "type":"address"
         }
      ],
      "name":"transferOwnership",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   }
];
export const wethAbi= [
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"src",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"guy",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"wad",
            "type":"uint256"
         }
      ],
      "name":"Approval",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"dst",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"wad",
            "type":"uint256"
         }
      ],
      "name":"Deposit",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"src",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"dst",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"wad",
            "type":"uint256"
         }
      ],
      "name":"Transfer",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"src",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"wad",
            "type":"uint256"
         }
      ],
      "name":"Withdrawal",
      "type":"event"
   },
   {
      "payable":true,
      "stateMutability":"payable",
      "type":"fallback"
   },
   {
      "constant":true,
      "inputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "name":"allowance",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "payable":false,
      "stateMutability":"view",
      "type":"function"
   },
   {
      "constant":false,
      "inputs":[
         {
            "internalType":"address",
            "name":"guy",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"wad",
            "type":"uint256"
         }
      ],
      "name":"approve",
      "outputs":[
         {
            "internalType":"bool",
            "name":"",
            "type":"bool"
         }
      ],
      "payable":false,
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "constant":true,
      "inputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "name":"balanceOf",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "payable":false,
      "stateMutability":"view",
      "type":"function"
   },
   {
      "constant":true,
      "inputs":[
         
      ],
      "name":"decimals",
      "outputs":[
         {
            "internalType":"uint8",
            "name":"",
            "type":"uint8"
         }
      ],
      "payable":false,
      "stateMutability":"view",
      "type":"function"
   },
   {
      "constant":false,
      "inputs":[
         
      ],
      "name":"deposit",
      "outputs":[
         
      ],
      "payable":true,
      "stateMutability":"payable",
      "type":"function"
   },
   {
      "constant":true,
      "inputs":[
         
      ],
      "name":"name",
      "outputs":[
         {
            "internalType":"string",
            "name":"",
            "type":"string"
         }
      ],
      "payable":false,
      "stateMutability":"view",
      "type":"function"
   },
   {
      "constant":true,
      "inputs":[
         
      ],
      "name":"symbol",
      "outputs":[
         {
            "internalType":"string",
            "name":"",
            "type":"string"
         }
      ],
      "payable":false,
      "stateMutability":"view",
      "type":"function"
   },
   {
      "constant":true,
      "inputs":[
         
      ],
      "name":"totalSupply",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "payable":false,
      "stateMutability":"view",
      "type":"function"
   },
   {
      "constant":false,
      "inputs":[
         {
            "internalType":"address",
            "name":"dst",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"wad",
            "type":"uint256"
         }
      ],
      "name":"transfer",
      "outputs":[
         {
            "internalType":"bool",
            "name":"",
            "type":"bool"
         }
      ],
      "payable":false,
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "constant":false,
      "inputs":[
         {
            "internalType":"address",
            "name":"src",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"dst",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"wad",
            "type":"uint256"
         }
      ],
      "name":"transferFrom",
      "outputs":[
         {
            "internalType":"bool",
            "name":"",
            "type":"bool"
         }
      ],
      "payable":false,
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "constant":false,
      "inputs":[
         {
            "internalType":"uint256",
            "name":"wad",
            "type":"uint256"
         }
      ],
      "name":"withdraw",
      "outputs":[
         
      ],
      "payable":false,
      "stateMutability":"nonpayable",
      "type":"function"
   }
];
